### ISSUE TITLE
screws do not fit with large heatsink supplied with new parallela boards

### ISSUE THREAD

**Issue by jonnew** [abopen/parallella-open-case#3]
The 16 mm screws to hold the fan in place protrude too far down and run into the large, black heatsink that is supplied with the parallela board. The 12 mm screws work great, so ship kits with 8X 12 mm screws and 4X 16mm screws and that should fit everyone's needs.

**Comment by 9600** [comment]
Thanks for the feedback, we'll look at the possibility of updating the BOM. However, since these are nylon you can just snip the bottom off the screws securing the fan in place.

**Comment by jonnew** [comment]
True enough.
